### ISSUE TITLE
[API-Wrapper] Missing mandatory field validation similar to edc-ui ("EDC API validation issue - Asset is creating without mandatory fields")

### ISSUE THREAD

**Issue by tmberthold** [sovity/edc-ce#1019]
### Description - What happened? *

Mandatory fields are checked via the UI but not when using the API-Wrapper directly. This means that in the MDS context e.g. assets can be created without the MDS-specific mandatory fields by directly using the API-Wrapper.

```
Create asset without mandatory fields (dataCategory field) using this API endpoint :

{{PROVIDER_EDC_MANAGEMENT_URL}}/wrapper/ui/pages/asset-page/assets - User able to create asset

Form EDC UI: Validation provided for mandatory fields while creating Asset.
API validation required for below sections :
- Create asset without mandatory field is allowing
- Create contract definition without mandatory field is allowing
- Create policy without mandatory field is allowing
```

### Expected Behavior *

`From API asset should not be created without mandatory fields.`

### Observed Behavior *

`From API asset is getting created without mandatory fields`

### Steps to Reproduce

```
Steps to reproduce the behavior:

Create asset with postman API :{{PROVIDER_EDC_MANAGEMENT_URL}}/wrapper/ui/pages/asset-page/assets
Validate mandatory fields shows an error message
```

### Context Information

EDC CE 10.0.0 and its UI

**Comment by AbdullahMuk** [comment]
Bug not considered as bug because:
- sovity API Wrapper is built in platform-agnostic manner as per general SaaS practices that allow for maximum flexibility. App developers bear the responsibility of adapt the relevant API elements according to their needs; which is what sovity does when it offers the CaaS with a UI. 

Also given the below factors, adapting the gap raised will require unnecessary effort for almost no added value over the current situation because:
   - (1) MDS predominantly offers a UI-centric product to its users 
   - (2) with no further evidence, sovity assumes that MDS only grants backend integration capability with MDS customers' systems in limited case at the condition that customers have advanced technical knowledge of API integrations. 
      - Assuming this scenario, sovity advises MDS to adapt its technical documentation to clearly hint to software architects what fields in the API should be filled. 

To conclude, there is no bug that requires fixing based on the description provided.

/cc @tmberthold for you to communicate back to MDS.
/cc @jkbquabeck
